apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: angular-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: angular-192.168.99.102.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: angular-app
          servicePort: 80
      # - path: /user-service
      #   backend:
      #     serviceName:
      #     servicePort: