apiVersion: v1
kind: Namespaces
metadata:
  name: angular-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespaces: angular-prod
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: angular-app
          image: iamdarshanshah/sample-angular-app
          ports:
            - containerPort: 80