apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: angular-app
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP #by default all pods run on TCP, to change it change the spec of deployment.
      targetPort: 80
  type: NodePort